In [66]:
import glob
import numpy as np
import matplotlib.pyplot as plt

import os

from pprint import pprint

import skimage.io
import sklearn.cluster
import sklearn.preprocessing

In [6]:
image_list = glob.glob("../images/*.png")

In [63]:
category_list = []
hist_list = []

for im_name in image_list:
    im = skimage.io.imread(im_name)
    data, _ = np.histogram(im, range=(0,32767))
    hist_list.append(data)

hist_list = np.asarray(hist_list)
pprint(hist_list)

[array([1382400,       0,       0,       0,       0,       0,       0,
             0,       0,       0], dtype=int64),
 array([1382400,       0,       0,       0,       0,       0,       0,
             0,       0,       0], dtype=int64),
 array([1376628,    4927,     697,     110,      23,      15,       0,
             0,       0,       0], dtype=int64)]
'break'
array([[1382400,       0,       0,       0,       0,       0,       0,
              0,       0,       0],
       [1382400,       0,       0,       0,       0,       0,       0,
              0,       0,       0],
       [1376628,    4927,     697,     110,      23,      15,       0,
              0,       0,       0]], dtype=int64)


In [59]:
kmeans = sklearn.cluster.KMeans(n_clusters=2, random_state=0).fit(hist_list)

In [61]:
kmeans.labels_

array([0, 0, 1])

In [73]:
os.makedirs("../images/class_0", exist_ok = True)
os.makedirs("../images/class_1", exist_ok = True)

for ind, label in enumerate(kmeans.labels_):
    im = skimage.io.imread(image_list[ind])
    _, filename = os.path.split(image_list[ind])
    if label==0:
        skimage.io.imsave(os.path.join("../images/class_0", filename), im)
    if label==1:
        skimage.io.imsave(os.path.join("../images/class_1", filename), im)

0


C:\Users\karhohs\AppData\Local\Continuum\Miniconda3\envs\bioimg\lib\site-packages\skimage\io\_io.py:132: UserWarning: ../images/class_0\testing_0.png is a low contrast image
  warn('%s is a low contrast image' % fname)


0


C:\Users\karhohs\AppData\Local\Continuum\Miniconda3\envs\bioimg\lib\site-packages\skimage\io\_io.py:132: UserWarning: ../images/class_0\testing_1.png is a low contrast image
  warn('%s is a low contrast image' % fname)


1


C:\Users\karhohs\AppData\Local\Continuum\Miniconda3\envs\bioimg\lib\site-packages\skimage\io\_io.py:132: UserWarning: ../images/class_1\testing_2.png is a low contrast image
  warn('%s is a low contrast image' % fname)
